### PR TITLE
Update maven wrapper

### PR DESCRIPTION
**Pull request by kazuki43zoo**

### CODE REVIEW

**Comment by hazendaz** [comment]
@kazuki43zoo Was it intential dropping the java file or potentially was that done due to how maven wrapper was changed in its defaults?  Checking as I have been updating that elsewhere using this command 'mvn -N org.apache.maven.plugins:maven-wrapper-plugin:wrapper -Dtype=source'.  I'd have to look again but I think its default is to apply the jar now which we intentially ignore.  Also probably never does it actually have to build the jar from the source unless its having trouble downloading the jar for some reason.

**Comment by kazuki43zoo** [comment]
@hazendaz Thanks for your comment! Sorry..., I didn't understand about java file(`-Dtype=source`). Therefore I has been removed it because it not change when `mvn wrapper:wrapper` without `-Dtype=source`. If need, i will add the java file using -Dtype=source option!

**Comment by hazendaz** [comment]
@kazuki43zoo Thanks!  Their new default is a bit weird.  Not a big deal. I wrote myself a git alias so I can just run 'git maven-wrapper' to use the style we had :)  If you add that to your .gitconfig under [alias] that makes it super easy and commits it too.

```
[alias]
    maven-wrapper = "!f() { mvn -N org.apache.maven.plugins:maven-wrapper-plugin:wrapper -Dtype=source; git add .; git commit -m '[mvn] Update maven wrapper'; }; f"
```

Typically, it should never need that file.  Its a fall back if for some reason it fails to download the file from central.  Only time I suspect that is an issue is with some network issue but just as likely to fail on any other dependency pull.

**Comment by hazendaz** [comment]
Oh and no worries to add, just wanted to confirm.  I had did this locally but not pushed across all of mybatis.  I rebased this project today and noticed the file was deleted and updated on my branch so I just wanted to check :)

**Pull request merged**
