### PR TITLE
Support the Chinese translation on test reference doc

### PR DESCRIPTION
**Pull request by awxiaoxian2020**

### CODE REVIEW

**Comment by awxiaoxian2020** [comment]
@kazuki43zoo I found that the samples are the same with `autoconfigure` , and it doesn't match with the `test` , do we need remove them?

**Comment by awxiaoxian2020** [comment]
@kazuki43zoo I have done the structure for the translations! I learned a lot from it :)

**Comment by kazuki43zoo** [comment]
@awxiaoxian2020 Thx!!

**Comment by awxiaoxian2020** [comment]
> @kazuki43zoo I found that the samples are the same with `autoconfigure` , and it doesn't match with the topic of `test` , do we need remove them?

@kazuki43zoo Could you please have a review about it?

**Comment by awxiaoxian2020** [comment]
I receive an CI error notice, I don't know what happened.
https://github.com/awxiaoxian2020/spring-boot-starter/actions/runs/2445622780

**Pull request merged**
