### PR TITLE
Improve to use constructor injection

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I've improved.

### CODE REVIEW

**Comment by eddumelendez** [comment]
@kazuki43zoo you can push directly to the repo... no need to send a PR.

**Comment by kazuki43zoo** [comment]
> no need to send a PR.

Hi @eddumelendez , Thanks for your advice !
I know it :). I am sending a PR to enable tracking my changes on the GitHub issue management. Are there problem ?

**Comment by eddumelendez** [comment]
I think that we can open an issue for that and close it with a direct commit. At the same time, with this we can enable to receive contribution for other people :)

**Comment by kazuki43zoo** [comment]
Hi @eddumelendez , your opinion is correct :)

**Pull request merged**
