### PR TITLE
Change to use executorType of SqlSessionFactory instead of SIMPLE by default

### PR DESCRIPTION
**Pull request by kazuki43zoo**
In currently implementation, executor type of `SqlSessionTemplate` is fixed to `SIMPLE` by default.
However, i think that it should be change to use `Configuration#getDefaultExecutorType()` of injected `SqlSessionFactory` .

What do you think ?

### CODE REVIEW

**Comment by eddumelendez** [comment]
It make sense with PR #25

**Comment by kazuki43zoo** [comment]
I think that this PR is independent with #25.
Default executor type of `SqlSessionTemplate` should use a executor type in config file by default.
If it specified expressly using spring's properties(or yaml),  specified executor type should be applied to `SqlSessionTemplate`.

What do you think ?

And, i've improved assertions for this.

**Comment by emacarron** [comment]
+1
I would say that if the executor-type property is not present we should not override the core's default (even if it is simple). I would just let that value to be null and create the template by calling to its constructor with only the sqlSessionFactory.

**Comment by kazuki43zoo** [comment]
@emacarron Thanks for your comment! I've applied your comment.

**Comment by kazuki43zoo** [comment]
Hi @emacarron, please change a milestone of this issue to the 1.1.0.

**Comment by emacarron** [comment]
Done. Thanks!

**Pull request merged**
