### PR TITLE
add condition to avoid auto scan mapper

### PR DESCRIPTION
**Pull request by vincent-ren**
`MapperScannerConfigurer` is also a way 
to register components and it create instances of `MapperFactoryBean`
`MapperScannerConfigurer#postProcessBeanDefinitionRegistry` that after this bean create.
if someone use `MapperScannerConfigurer` rather than `MapperScan` to register components,  this can be make `MapperScannerRegistrarNotFoundConfiguration` created, it will automatically register components based on the same component-scanning path as Spring Boot itself.

### Remain Tasks

- [x] Add test

### CODE REVIEW

**Comment by kazuki43zoo** [comment]
@vincent-ren thanks for your contributing! Could you add a test case?

**Comment by vincent-ren** [comment]
@kazuki43zoo oh, this is an conditional on miss bean enhance, not easy to add a test case, also I didn`t find a test case about `MapperScannerRegistrarNotFoundConfiguration`. But I can provider a sample to prove this is a enhancement.

**Comment by kazuki43zoo** [comment]
I've move milestone to 2.1.x because there is case that broken backwards compatibility with 2.0.0 or before.

@vincent-ren 
If you have an actual problem in your application, please provide a detail information.

Thanks

**Comment by kazuki43zoo** [comment]
Hi @vincent-ren,

Thanks for your contributing. I've fixed via gh-328.

**Comment by vincent-ren** [comment]
@kazuki43zoo It`s my pleasure

**Pull request closed without merging**
